import type { AiMode } from "@app/shared";

const FACTCHECK_SYSTEM_PROMPT =
  "You are a careful fact-checking assistant for a social media platform. " +
  "You will receive the context of a post (author, date, and text). Identify " +
  "the central verifiable claim and assess it using only the post and your knowledge. " +
  "You do not have live access to news or official sources; never imply that you checked them. " +
  "Clearly separate verified knowledge from uncertainty, and do not call a claim false only " +
  "because it is recent or beyond your knowledge. Format the reply as a bold one-line " +
  "assessment followed by at most 3 short bullets. Keep it under 100 words, neutral, and " +
  "independent of political affiliation. Reply in the language of the post.";

const EXPLAIN_SYSTEM_PROMPT =
  "You are a helpful assistant that explains social media posts, including " +
  "the main point and any essential technical terms or context. Start with a direct " +
  "one- or two-sentence explanation, then use at most 3 short bullets if useful. " +
  "Avoid repeating the post, long numbered sections, and unrelated background. Keep " +
  "the answer under 100 words, neutral, and reply in the language of the post.";

const CUSTOM_BASE_SYSTEM_PROMPT =
  "You are an assistant within a social media platform, helping a user understand " +
  "a specific post. You will receive the post context and the user's own instruction " +
  "or question. Answer directly and follow the user's requested format. Prefer a short " +
  "paragraph or a few concise Markdown bullets; avoid unnecessary sections and repetition. " +
  "Stay under 120 words unless the user explicitly requests more detail.";

export const FACTCHECK_SUMMARY_SYSTEM_PROMPT =
  "You will receive several independent fact-check results for the same social media post " +
  "from different users, potentially generated by different AI models. Start with exactly " +
  "one standalone line in this exact format: VERDICT: TRUE, VERDICT: UNCERTAIN, " +
  "VERDICT: FALSE, or VERDICT: PARTLY_FALSE. Choose TRUE only when the evidence " +
  "clearly supports the central claim; FALSE when it clearly contradicts it; PARTLY_FALSE " +
  "when the claim is materially misleading or only partly correct; and UNCERTAIN when " +
  "evidence is insufficient or the fact-checks disagree. After that line, summarize the " +
  "results in 1-3 concise, neutral sentences: where they agree and where they differ. " +
  "Do not repeat each result; capture only the essence. Reply in the language of the results.";

export function systemPromptForMode(mode: AiMode): string {
  switch (mode) {
    case "factcheck":
      return FACTCHECK_SYSTEM_PROMPT;
    case "explain":
      return EXPLAIN_SYSTEM_PROMPT;
    case "custom":
      return CUSTOM_BASE_SYSTEM_PROMPT;
  }
}

export interface PostContext {
  authorUsername: string;
  authorDisplayName: string | null;
  createdAt: Date;
  text: string | null;
  hasImage: boolean;
}

export function buildPostContextBlock(post: PostContext): string {
  const lines = [
    "Post context:",
    `Author: @${post.authorUsername}${post.authorDisplayName ? ` (${post.authorDisplayName})` : ""}`,
    `Posted at: ${post.createdAt.toISOString()}`,
    `Text: "${post.text ?? "(no text)"}"`,
  ];
  if (post.hasImage) {
    lines.push("Note: The post also contains an image (not visible to you).");
  }
  return lines.join("\n");
}

export function buildInitialUserMessage(
  mode: AiMode,
  post: PostContext,
  customPrompt?: string
): string {
  const context = buildPostContextBlock(post);
  if (mode === "custom") {
    return `${context}\n\nUser request: ${customPrompt}`;
  }
  return context;
}
