import type { AiMode } from "@app/shared";

const FACTCHECK_SYSTEM_PROMPT =
  "You are a careful fact-checking assistant for a social media platform. " +
  "You will receive the context of a post (author, date, and text). Identify " +
  "verifiable factual claims, assess their accuracy to the best of your knowledge, " +
  "point out missing context or nuance, and clearly state uncertainty when unsure. " +
  "Be concise, neutral, and independent of political affiliation. Reply in the language of the post.";

const EXPLAIN_SYSTEM_PROMPT =
  "You are a helpful assistant that explains social media posts, including " +
  "technical terms, references, and historical or social context needed for " +
  "understanding. Be concise, neutral, informative, and reply in the language of the post.";

const CUSTOM_BASE_SYSTEM_PROMPT =
  "You are an assistant within a social media platform, helping a user understand " +
  "a specific post. You will receive the post context and the user's own instruction " +
  "or question. Follow the user's instruction as closely as possible, using the post as context.";

export const FACTCHECK_SUMMARY_SYSTEM_PROMPT =
  "You will receive several independent fact-check results for the same social media post " +
  "from different users, potentially generated by different AI models. Summarize them " +
  "in 1-3 concise, neutral sentences: where they agree and where they differ. Do not " +
  "repeat each result; capture only the essence. Reply in the language of the results.";

export function systemPromptForMode(mode: AiMode): string {
  switch (mode) {
    case "factcheck":
      return FACTCHECK_SYSTEM_PROMPT;
    case "explain":
      return EXPLAIN_SYSTEM_PROMPT;
    case "custom":
      return CUSTOM_BASE_SYSTEM_PROMPT;
  }
}

export interface PostContext {
  authorUsername: string;
  authorDisplayName: string | null;
  createdAt: Date;
  text: string | null;
  hasImage: boolean;
}

export function buildPostContextBlock(post: PostContext): string {
  const lines = [
    "Post context:",
    `Author: @${post.authorUsername}${post.authorDisplayName ? ` (${post.authorDisplayName})` : ""}`,
    `Posted at: ${post.createdAt.toISOString()}`,
    `Text: "${post.text ?? "(no text)"}"`,
  ];
  if (post.hasImage) {
    lines.push("Note: The post also contains an image (not visible to you).");
  }
  return lines.join("\n");
}

export function buildInitialUserMessage(
  mode: AiMode,
  post: PostContext,
  customPrompt?: string
): string {
  const context = buildPostContextBlock(post);
  if (mode === "custom") {
    return `${context}\n\nUser request: ${customPrompt}`;
  }
  return context;
}
